import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const read = (path: string) => readFileSync(resolve(root, path), "utf8");
const json = (path: string) => JSON.parse(read(path));
const install = read("install.md"), release = json("release.json");
const client = read("plugins/client/blaze-client.mjs"), skill = read("skill.md");
assert.match(release.version,/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/);
assert.ok(skill.includes(`version: "${release.version}"`));
assert.ok(install.startsWith(`# Install Blaze ${release.version}\n`));
assert.ok(client.includes(`CLIENT_VERSION = "${release.version}"`));
assert.ok(client.includes(`CLIENT_CONTRACT = ${release.client_contract};`));
assert.equal(read("plugins/claude-code/skills/blaze/SKILL.md"),skill,"Skill copy drift");
for (const path of ["plugins/claude-code/blaze-client.mjs","plugins/claude-code/skills/blaze/blaze-client.mjs"]) {
  assert.equal(read(path),client,`Self-contained plugin client drift: ${path}`);
}
assert.equal(install.trimEnd().split("\n").at(-1),"BLAZE-INSTALL-END");
assert.ok(install.includes("/api/skill-release") && install.includes("--max-redirs 0"));
const marketplace = json(".claude-plugin/marketplace.json"), plugin = json("plugins/claude-code/.claude-plugin/plugin.json");
assert.equal(marketplace.name,"blaze");assert.equal(marketplace.plugins.length,1);
assert.equal(marketplace.plugins[0].source,"./plugins/claude-code");assert.equal(plugin.name,"blaze");
for (const version of [plugin.version,marketplace.metadata.version,marketplace.plugins[0].version]) assert.equal(version,release.version);
const claudeHooks = json("plugins/claude-code/hooks/hooks.json").hooks;
const codexHooks = json("plugins/codex/hooks.json").hooks;
const cursorHooks = json("plugins/cursor/hooks.json");
for(const hooks of [claudeHooks,codexHooks]) assert.deepEqual(Object.keys(hooks),["UserPromptSubmit"]);
assert.equal(claudeHooks.UserPromptSubmit[0].hooks[0].command,'node "${CLAUDE_PLUGIN_ROOT}/blaze-client.mjs" hook --tool claude');
assert.equal("statusMessage" in claudeHooks.UserPromptSubmit[0].hooks[0],false);
assert.equal(codexHooks.UserPromptSubmit[0].hooks[0].command,"~/.codex/blaze-hook.sh");
assert.equal(cursorHooks.version,1);assert.deepEqual(Object.keys(cursorHooks.hooks),["sessionStart"]);
assert.equal(cursorHooks.hooks.sessionStart[0].command,"./blaze-hook.sh");
assert.equal(Bun.spawnSync(["bash","-n",resolve(root,"plugins/codex/blaze-hook.sh")]).exitCode,0);
assert.equal(Bun.spawnSync(["bash","-n",resolve(root,"plugins/cursor/blaze-hook.sh")]).exitCode,0);
for(const path of ["plugins/opencode/blaze.js","plugins/client/blaze-client.mjs"]) new Bun.Transpiler({loader:"js"}).transformSync(read(path));
assert.ok(read("plugins/opencode/blaze.js").includes('"experimental.chat.system.transform"'));
assert.ok(!read("plugins/opencode/blaze.js").includes('"chat.message"'));
console.log("Portable skill, plugin copies, release metadata and local hook syntax agree.");
